import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ApolloWrapper from '@/api/graphql/apollo';

import './globals.css';
import { Toaster } from 'sonner';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Inicio de sesión',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>{children}</ApolloWrapper>
        <Toaster richColors />
      </body>
    </html>
  );
}
